//
//  IconDescription.swift
//  FoodForThought
//
//  Created by Wu, Andrew on 7/15/15.
//  Copyright (c) 2015 Davidson College Mobile App Team. All rights reserved.
//

import Foundation

struct IconDescription{
    let descriptions = [
        "FSD": "This dish was prepared from scratch.\n ",
        "FS": "This restaurant prepares meals from scratch.\n",
        "SE": "An ingredient in this dish is in season.\n",
        "LD": "An ingredient in this dish comes from a local producer.\n ",
        "L": "This restaurant provides food options from local farms that are within 250 miles.\n",
        "AI":  "Allergen information is available upon request.\n ",
        "CA":  "This restaurant offers catering services.\n ",
        "FD":  "This restaurant frequently donates prepared food to charities, churches, or food banks. \n ",
        "MD":  "This restaurant frequently contributes monetary donations to charities.\n ",
        "VO":  "This restaurant promotes volunteering opportunities to its employees.\n ",
        "C":  "This restaurant composts food scraps.\n ",
        "LA":  "This restaurant sources alcoholic beverages from local breweries and wineries.\n ",
        "R":  "This restaurant recycles appropriate materials.\n ",
        
        "CE":  "This food item is a good source of carb energy. Carbohydrates are the body’s preferred source of fuel and provide important B vitamins and fiber. \n",
        "ES":  "This restaurant uses Energy Star appliances to reduce energy consumption. \n",
        "HF":  "This food item is a good source of healthy fat. Healthy fats add flavor and satiety to food, are heart healthy, prevent inflammation, aid in the absorption of fat-soluble vitamins, and provide energy.\n ",
        "PP":  "This food item is a good source of protein. Proteins are the building blocks of most body tissues and carry out metabolic properties, such as transporting oxygen throughout the body.\n ",
        "VN":  "This food item is rich in nutrients such as essential vitamins and minerals. Nutrient-rich foods are important for immune system health, energy metabolism, and disease prevention.\n ",

        "Humane": "Humane:\n\n",
        "Eco": "Ecologicaly Sound:\n\n",
        "Fair": "Fair:\n\n",
        
        "CBF": "-This restaurant serves Certified Bird Friendly coffee.\n",
        "CLS": "-This restaurant offers Certified Local Sustainable (Local Food Plus) food.\n",
        "IFO": "-This restaurant serves food certified by the International Federation of Organic Agriculture Movements.\n",
        "DCB" : "-This restaurant offers Demeter Certified Biodynamic food.\n",
        "EUO" : "-This restaurant offers certified European Union Organic food.\n",
        "FAC" : "-This restaurant offers food that is Food Alliance Certified.\n",
        "MSC" : "-This restaurant serves Marine Stewardship Council Blue Seafood.\n",
        "MBA": "-This restaurant offers Monterey Bay Seafood Watch \"Best Choice\" Seafood.\n",
        "RAC" : "-This restaruant offers Rainforest Alliance Certified food.\n",
        "USDA" : "-This restaurant offers food that is USDA Certified Organic.\n",
        "EFT": "-This restaurant offers Ecocert Fair Trade certified food.\n",
        "FFS":  "-This restaurant offers food that is certified by the Fair Food Standards Council.\n",
        "FL" : "-This restaurant serves food that is Fair for Life certified.\n",
        "FT" : "-This restaurant serves food that is certified Fairtrade.\n",
        "FW" : "-This restaurant offers food that is FairWild Certified.\n",
        "FJC" : "-This restaurant offers food that is Food Justice Certified.\n",
        "SPS" : "-This restaurant offers food that has recieved the Small Producers’ Symbol.\n",
        "AGA":  "-This restaurant serves food that has been certified by the American Grassfed Association.\n",
        "AHC": "-This restaurant offers food that is American Humane Certified.\n",
        "AWA": "-This restaurant offers food that is Animal Welfare Approved.\n",
        "CHR" : "-This restaurant offers food that is Certified Humane Raised and Handled.\n",
        "GAP" : "-This restaurant offers food certified by the Global Animal Partnership.\n",
 
        
        "CBFD": "-This coffee is Certified Bird Friendly.\n",
        "CLSD": "-An ingredient in this dish is Certified Local Sustainable (Local Food Plus).\n",
        "IFOD": "-An ingredient in this dish is certified by the International Federation of Organic Agriculture Movements.\n",
        "DCBD" : "-An ingredient in this dish is Demeter Certified Biodynamic.\n",
        "EUOD" : "-An ingredient in this dish is certfied European Union Organic.\n",
        "FACD" : "-An ingredient in this dish is Food Alliance Certified.\n",
        "MSCD" : "-This dish contains Marine Stewardship Council Blue Seafood.\n",
        "MBAD": "-This dish contains Monterey Bay Seafood Watch \"Best Choice\" Seafood.\n",
        "PHCD" :  "-An ingredint in this dish is Protected Harvest Certified.\n",
        "RACD" : "-An ingredient in this dish is Rainforest Alliance Certified.\n",
        "USDAD" : "-An ingredient in this dish is USDA Certified Organic.\n",
        "EFTD": "-An ingredient in this dish is Ecocert Fair Trade certified.\n",
        "FFSD":  "-An ingredient in this dish is Fair Food Standards Council certified.\n",
        "FLD" : "-An ingredient in this dish is Fair for Life certified.\n",
        "FTD" : "-An ingredient in this dish is Fairtrade certified.\n",
        "FWD" : "-An ingredient in this dish is FairWild Certified.\n",
        "FJCD" : "-An ingredient in this dish is Food Justice Certified.\n",
        "SPSD" : "-An ingredient in this dish has recieved the Small Producers’ Symbol.\n",
        "AGAD":  "-An ingredient in this dish has been certified by the American Grassfed Association.\n",
        "AHCD": "-An ingredient in this dish is American Humane Certified.\n",
        "AWAD": "-An ingredient in this dish is Animal Welfare Approved.\n",
        "CHRD" : "-An ingredient in this dish is Certified Humane Raised and Handled.\n",
        "GAPD" : "-An ingredient in this dish has been certified by the Global Animal Partnership.\n",
    ]
    
    let urls = [
        "FS":  "http://food.davidsonsustainability.org",
        "L":  "http://food.davidsonsustainability.org",
        "SE": "http://food.davidsonsustainability.org",
        "FSD": "http://food.davidsonsustainability.org",
        "AI":  "http://food.davidsonsustainability.org",
        "CA":  "http://food.davidsonsustainability.org",
        "FD":  "http://food.davidsonsustainability.org",
        "MD":  "http://food.davidsonsustainability.org",
        "VO":  "http://food.davidsonsustainability.org",
        "C":  "http://food.davidsonsustainability.org",
        "LA":  "http://food.davidsonsustainability.org",
        "R":  "http://food.davidsonsustainability.org",
        "LD": "http://food.davidsonsustainability.org",
        "CE":  "http://food.davidsonsustainability.org",
        "ES":  "http://food.davidsonsustainability.org",
        "HF":  "http://food.davidsonsustainability.org",
        "PP":  "http://food.davidsonsustainability.org",
        "VN":  "http://food.davidsonsustainability.org",
        
        "Humane": "http://food.davidsonsustainability.org",
        "Eco": "http://food.davidsonsustainability.org",
        "Fair": "http://food.davidsonsustainability.org",
        
        "COB": "http://www.organicfederation.ca",
        "Certified Bird Friendly coffee": "http://nationalzoo.si.edu/scbi/migratorybirds/coffee/",
        "Certified Local Sustainable (Local Food Plus)": "http://landfoodpeople.ca",
        "International Federation of Organic Agriculture Movements": "http://www.ifoam.bio",
        "Demeter Certified Biodynamic" : "http://www.demeterbta.com/certification.html",
        "European Union Organic" : "http://ec.europa.eu/agriculture/organic/index_en.htm",
        "Food Alliance Certified" : "http://foodalliance.org",
        "Marine Stewardship Council Blue Ecolabel" : "https://www.msc.org",
        "Monterey Bay Seafood Watch \"Best Choice\" Seafood": "http://www.seafoodwatch.org",
        "Protected Harvest Certified" :  "http://www.protectedharvest.org",
        "Rainforest Alliance Certified" : "http://www.rainforest-alliance.org/work/agriculture",
        "USDA Certified Organic" : "http://www.usda.gov/wps/portal/usda/usdahome?contentidonly=true&contentid=organic-agriculture.html",
        "Ecocert Fair Trade": "http://www.ecocert.com/en/fair-trade",
        "Fair Food Standards Council":  "http://fairfoodstandards.org",
        "Fair for Life" : "http://www.fairforlife.org",
        "Fairtrade" : "http://www.fairtradeusa.org",
        "FairWild Certified" : "http://www.fairwild.org",
        "Food Justice Certified" : "http://agriculturaljusticeproject.org",
        "Small Producers’ Symbol" : "http://www.tusimbolo.org",
        "American Grassfed Association":  "http://www.americangrassfed.org",
        "American Humane Certified": "http://www.americanhumane.org/animals/programs/farm-animal-welfare.html",
        "Animal Welfare Approved": "http://animalwelfareapproved.org",
        "Certified Humane Raised and Handled" : "http://certifiedhumane.org",
        "Global Animal Partnership" : "http://www.globalanimalpartnership.org",
        
    ]
}